import { useState, useRef, useCallback } from 'react'
import { AgentState, AgentStep, StepStatus, LogEntry, SSEFrame, UsageMetrics } from '../types/agent'

const INITIAL_STEP_STATUSES: Record<AgentStep, StepStatus> = {
  planner: 'idle',
  searcher: 'idle',
  summarizer: 'idle',
  critic: 'idle',
  report_generator: 'idle',
}

const INITIAL_STATE: AgentState = {
  status: 'idle',
  currentStep: null,
  stepStatuses: { ...INITIAL_STEP_STATUSES },
  subQuestions: [],
  completedQuestions: [],
  logs: [],
  finalReport: '',
  topic: '',
  retryCount: 0,
  total_tokens: 0,
  wordCount: 0,
}

function formatTimestamp(): string {
  const now = new Date()
  const hh = String(now.getHours()).padStart(2, '0')
  const mm = String(now.getMinutes()).padStart(2, '0')
  const ss = String(now.getSeconds()).padStart(2, '0')
  return `${hh}:${mm}:${ss}`
}

function createLog(message: string, type: LogEntry['type'] = 'info'): LogEntry {
  return {
    id: `${Date.now()}-${Math.random()}`,
    timestamp: formatTimestamp(),
    message,
    type,
  }
}

function mockResearch(topic: string, onFrame: (frame: SSEFrame) => void): () => void {
  const questions = [
    `What is ${topic}?`,
    `History of ${topic}`,
    `Future of ${topic}`,
    `Key challenges in ${topic}`,
  ]

  const mockReport = `# Research Report: ${topic}

## Executive Summary

This comprehensive analysis explores ${topic} in depth, examining its fundamental principles, historical development, and future trajectory. Through extensive research and synthesis, we have identified key insights and emerging patterns.

## Background

${topic} represents a fascinating area of study with significant implications for modern society. Researchers and practitioners have been exploring this domain for decades, uncovering layers of complexity and nuance.

The foundational concepts emerged from early theoretical frameworks, which have since evolved into sophisticated methodologies and practical applications.

## Key Findings

### Core Principles

The fundamental principles governing ${topic} can be summarized across several dimensions:

- **Structural complexity**: The domain exhibits multi-layered interdependencies that require holistic analysis
- **Dynamic evolution**: Continuous adaptation characterizes the field, driven by technological and societal shifts
- **Cross-disciplinary relevance**: Insights from adjacent fields consistently enrich our understanding

### Historical Context

The development of ${topic} spans multiple eras, each marked by significant breakthroughs:

1. **Early foundations** — Initial theoretical frameworks established core vocabulary
2. **Maturation phase** — Empirical validation and refinement of models
3. **Modern synthesis** — Integration with computational methods and data science

## Challenges and Opportunities

Despite significant progress, several challenges persist:

**Scalability** remains a primary concern, as approaches that work at small scales often break down under real-world conditions. **Data quality** issues introduce systematic biases that require careful mitigation. **Interdisciplinary communication** gaps slow knowledge transfer between communities.

However, these challenges present corresponding opportunities for innovation and differentiated contribution.

## Future Outlook

The trajectory of ${topic} points toward increasing automation, deeper integration with AI systems, and broader societal impact. Emerging research directions include:

- Novel computational frameworks for modeling complex phenomena
- Human-AI collaborative approaches to decision-making
- Cross-cultural and global applications

## Conclusion

${topic} stands at an inflection point, with foundational work now enabling transformative applications. Continued investment in both theoretical and applied research will be essential to realizing the field's full potential.

---

*Report generated by ResearchAgent using LangGraph multi-step reasoning pipeline.*`

  const chunks = mockReport.match(/.{1,40}/g) || []
  let i = 0

  const logMessages: Array<{ msg: string; type: LogEntry['type'] }> = [
    { msg: 'Initializing research pipeline...', type: 'info' },
    { msg: `Topic received: "${topic}"`, type: 'info' },
    { msg: 'Planner node activated', type: 'info' },
    { msg: 'Decomposing research query into sub-questions', type: 'info' },
    { msg: `Generated ${questions.length} parallel search queries`, type: 'success' },
    { msg: 'Planner node complete', type: 'success' },
    { msg: 'Searcher node activated', type: 'info' },
    { msg: 'Dispatching parallel search workers', type: 'info' },
    { msg: `Search worker 1: "${questions[0]}"`, type: 'info' },
    { msg: `Search worker 2: "${questions[1]}"`, type: 'info' },
    { msg: `Search worker 3: "${questions[2]}"`, type: 'info' },
    { msg: `Search worker 4: "${questions[3]}"`, type: 'info' },
    { msg: 'All search workers returned results', type: 'success' },
    { msg: 'Aggregating search results', type: 'info' },
    { msg: 'Searcher node complete', type: 'success' },
    { msg: 'Summarizer node activated', type: 'info' },
    { msg: 'Processing 24 source documents', type: 'info' },
    { msg: 'Extracting key insights from sources', type: 'info' },
    { msg: 'Summary synthesis complete', type: 'success' },
    { msg: 'Summarizer node complete', type: 'success' },
    { msg: 'Critic node activated', type: 'warning' },
    { msg: 'Evaluating summary quality and coverage', type: 'warning' },
    { msg: 'Quality threshold met — proceeding', type: 'success' },
    { msg: 'Critic node complete', type: 'success' },
    { msg: 'Report generator activated', type: 'info' },
    { msg: 'Composing final structured report', type: 'info' },
    { msg: 'Streaming report content...', type: 'info' },
  ]

  let logIndex = 0

  const timeline: Array<{ tick: number; fn: () => void }> = [
    { tick: 0, fn: () => onFrame({ type: 'step_start', node: 'planner' }) },
    { tick: 2, fn: () => onFrame({ type: 'questions', data: questions }) },
    { tick: 4, fn: () => onFrame({ type: 'step_complete', node: 'planner' }) },
    { tick: 5, fn: () => onFrame({ type: 'step_start', node: 'searcher' }) },
    { tick: 12, fn: () => onFrame({ type: 'step_complete', node: 'searcher' }) },
    { tick: 13, fn: () => onFrame({ type: 'step_start', node: 'summarizer' }) },
    { tick: 18, fn: () => onFrame({ type: 'step_complete', node: 'summarizer' }) },
    { tick: 19, fn: () => onFrame({ type: 'step_start', node: 'critic' }) },
    { tick: 23, fn: () => onFrame({ type: 'step_complete', node: 'critic' }) },
    { tick: 24, fn: () => onFrame({ type: 'step_start', node: 'report_generator' }) },
  ]

  let chunkIndex = 0

  const interval = setInterval(() => {
    timeline.forEach(({ tick, fn }) => {
      if (i === tick) fn()
    })

    if (i >= 24 && chunkIndex < chunks.length) {
      onFrame({ type: 'report_chunk', data: chunks[chunkIndex] })
      chunkIndex++
    }

    if (i % 2 === 0 && logIndex < logMessages.length) {
      const l = logMessages[logIndex]
      onFrame({ type: 'log', data: { message: l.msg, type: l.type } })
      logIndex++
    }

    if (i >= 24 + chunks.length + 2) {
      onFrame({ type: 'done', node: 'report_generator' })
      clearInterval(interval)
    }

    i++
  }, 300)

  return () => clearInterval(interval)
}

export function useResearchAgent() {
  const [state, setState] = useState<AgentState>(INITIAL_STATE)
  const [mockMode, setMockMode] = useState(false)
  const cleanupRef = useRef<(() => void) | null>(null)
  const eventSourceRef = useRef<EventSource | null>(null)

  const processFrame = useCallback((frame: SSEFrame) => {
    setState(prev => {
      const next = { ...prev }

      switch (frame.type) {
        case 'step_start': {
          if (!frame.node) break
          const newStatuses = { ...prev.stepStatuses }
          if (prev.currentStep && prev.currentStep !== frame.node) {
            newStatuses[prev.currentStep] = 'completed'
          }
          newStatuses[frame.node] = 'active'
          next.stepStatuses = newStatuses
          next.currentStep = frame.node
          break
        }
        case 'step_complete': {
          if (!frame.node) break
          const newStatuses = { ...prev.stepStatuses }
          newStatuses[frame.node] = 'completed'
          next.stepStatuses = newStatuses
          if (prev.currentStep === frame.node) {
            next.currentStep = null
          }
          break
        }
        case 'questions': {
          if (Array.isArray(frame.data)) {
            next.subQuestions = frame.data as string[]
          }
          break
        }
        case 'log': {
          if (frame.data && typeof frame.data === 'object' && !Array.isArray(frame.data)) {
            const d = frame.data as { message?: string; type?: LogEntry['type'] }
            next.logs = [
              ...prev.logs,
              createLog(d.message || '', d.type || 'info'),
            ]
          }
          break
        }
        case 'usage': {
          if (frame.data && typeof frame.data === 'object' && !Array.isArray(frame.data)) {
            const d = frame.data as UsageMetrics
            next.total_tokens = d.total_tokens
          }
          break
        }
        case 'report_chunk': {
          if (typeof frame.data === 'string') {
            const newReport = prev.finalReport + frame.data
            next.finalReport = newReport
            next.wordCount = newReport.split(/\s+/).filter(Boolean).length
          }
          break
        }
        case 'done': {
          next.status = 'complete'
          next.currentStep = null
          if (frame.node) {
            const newStatuses = { ...prev.stepStatuses }
            newStatuses[frame.node] = 'completed'
            next.stepStatuses = newStatuses
          }
          next.logs = [
            ...prev.logs,
            createLog('Research complete. Report ready.', 'success'),
          ]
          break
        }
      }

      return next
    })
  }, [])

  const startResearch = useCallback((topic: string) => {
    if (cleanupRef.current) cleanupRef.current()
    if (eventSourceRef.current) eventSourceRef.current.close()

    setState({
      ...INITIAL_STATE,
      status: 'researching',
      topic,
      logs: [createLog(`Starting research on: "${topic}"`, 'info')],
    })

    if (mockMode) {
      cleanupRef.current = mockResearch(topic, processFrame)
    } else {
      const url = `http://localhost:8000/research/stream?topic=${encodeURIComponent(topic)}`
      const es = new EventSource(url)
      eventSourceRef.current = es

      es.onmessage = (event) => {
        try {
          const frame = JSON.parse(event.data) as SSEFrame
          processFrame(frame)
        } catch {
          // ignore parse errors
        }
      }

      es.onerror = () => {
        setState(prev => {
          if (prev.status === 'complete') {
            return prev
          }
          return {
            ...prev,
            status: 'error',
            logs: [...prev.logs, createLog('Connection error', 'error')],
          }
        })
        es.close()
      }

      cleanupRef.current = () => es.close()
    }
  }, [mockMode, processFrame])

  const stopResearch = useCallback(() => {
    if (cleanupRef.current) {
      cleanupRef.current()
      cleanupRef.current = null
    }
    if (eventSourceRef.current) {
      eventSourceRef.current.close()
      eventSourceRef.current = null
    }
    setState(prev => ({
      ...prev,
      status: 'idle',
      logs: [...prev.logs, createLog('Research stopped by user.', 'warning')],
    }))
  }, [])

  const resetResearch = useCallback(() => {
    if (cleanupRef.current) cleanupRef.current()
    if (eventSourceRef.current) eventSourceRef.current.close()
    setState(INITIAL_STATE)
  }, [])

  const toggleMockMode = useCallback(() => {
    setMockMode(prev => !prev)
  }, [])

  const markQuestionComplete = useCallback((question: string) => {
    setState(prev => ({
      ...prev,
      completedQuestions: [...prev.completedQuestions, question],
    }))
  }, [])

  return {
    state,
    mockMode,
    startResearch,
    stopResearch,
    resetResearch,
    toggleMockMode,
    markQuestionComplete,
  }
}
